df<-read.csv("result.csv", header=F)
colnames(df)<-c("TTM","QuotedPrice","InitialRate","FinalRateNss","FinalRateSpline","CalculatedPriceNss","CalculatedPriceSpline")
max<-max(df[,c(3,5)])
min<-min(df[,c(3,5)])
maxP<-max(df[,c(6,7)])
minP<-min(df[,c(6,7)])
save<-par(mfrow=c(2,1))
x<-(df$TTM)
with(df, {
	plot(x, InitialRate,type="o",pch=3,ylim=c(min,max), main="Comparison of Term Structures", ylab="Spot rates in %", xlab="Time to maturity",log="x")
	lines(x, FinalRateNss, col="red", type="o",pch=3)
	lines(x, FinalRateSpline, col="green", type="o",pch=3)
	legend("topleft", legend=c("Starting Curve", "Nelson Siegel Svensson", "Cubic Splines"), lty=1, col=c("black","red","green"), cex=0.8)
})
with(df, {
	plot(x, QuotedPrice,type="o",pch=3,ylim=c(minP,maxP), main="Comparison of Bond Prices", ylab="Bond prices in CHF", xlab="Time to maturity",log="x")
	lines(x, CalculatedPriceNss, col="red", type="o",pch=3)
	lines(x, CalculatedPriceSpline, col="green", type="o",pch=3)
	legend("topleft", legend=c("Quoted Price", "Nelson Siegel Svensson","Cubic Splines"), lty=1, col=c("black","red", "green"),cex=0.8)
})
par(save)
