df<-read.csv("result.csv", header=F)
colnames(df)<-c("TTM","InitialRate","FinalRate","QuotedPrice","CalculatedPrice")
max<-max(df[,c(2,3)])
min<-min(df[,c(2,3)])
maxP<-max(df[,c(4,5)])
minP<-min(df[,c(4,5)])
save<-par(mfrow=c(2,1))
x<-(df$TTM)
with(df, {
	plot(x, InitialRate,type="o",pch=3,ylim=c(min,max), main="Comparison of Term Structures", ylab="Spot rates in %", xlab="Time to maturity",log="x")
	lines(x, FinalRate, col="red", type="o",pch=3)
	legend("topleft", legend=c("Starting Curve", "Fitted Curve"), lty=1, col=c("black","red"))
})
with(df, {
	plot(x, QuotedPrice,type="o",pch=3,ylim=c(minP,maxP), main="Comparison of Bond Prices", ylab="Bond prices in CHF", xlab="Time to maturity",log="x")
	lines(x, CalculatedPrice, col="red", type="o",pch=3)
	legend("topleft", legend=c("Quoted Price", "Calculated Price"), lty=1, col=c("black","red"))
})
par(save)
